[package]
name = "cidre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#[lib]
#crate-type = ["staticlib"]

#[lib]
#crate-type = ["cdylib"]


[profile.release]
lto = true
strip = "debuginfo"
panic = "abort"