[workspace]
resolver = "2"

members = [
  "cidre",
  "cidre-macros",
]

exclude = [
  "cargo-box"
]

# [profile.dev]
# opt-level = 1

# [profile.dev.package."*"]
# opt-level = 3

[profile.release]
lto = true
strip = "debuginfo"
panic = "abort"


