[package]
name = "cidre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ["full"]

full = [
  "private",

  "blocks",
  "async",

  "am",
  "at",
  "ca",
  "ci",
  "cm",
  "ct",
  "av",
  "cf",
  "cg",
  "ns",
  "vt",
  "sc",
  "mtl",
  "mlc",
  "cv",
  "objc",
  "mps",
  "mpsg",
  "dispatch",
  "simd",
  "cat",
  "vn",
  "io"
]

# Turn on private API
private = []
async = ["dep:parking_lot"]

blocks = []
cf = []
cat = []
simd = []
am = ["private", "cf", "dep:tokio"]
at = ["cf", "cat"]
av = ["ns"]
ca = ["ns"]
sc = ["ns"]
cm = ["at"]
cv = ["cf"]
ci = ["cf", "ns"]
cg = ["cf", "io"]
objc = ["dep:cidre-macros"]
ns = ["objc"]
vt = ["cf", "cv", "cg", "cm"]
dispatch = ["cf", "ns"]
io = ["cf"]
sn = ["ns"]
vn = ["ns"]
ct = ["cf", "cg"]
mtl = ["ns"]
mlc = ["mtl"]
mps = ["mtl"]
mpsg = ["mps"]

[dependencies]

tokio = { version = "1", optional = true, default-features = false, features = ["macros", "rt", "rt-multi-thread", "time", "net", "process", "io-util"] }
parking_lot = { version = "0.12.0", optional = true }
cidre-macros = { optional = true, path = "../cidre-macros"}

[dev-dependencies]
criterion = "0.3"
# rt = { path = "../../rt"}
# ndarray = "0.15"
# linfa = "0.6.1"
# linfa-clustering = "0.6.1"
# linfa-reduction = "0.6.1"
clap = { version = "4.1.4", features = ["default", "derive"] }

[[bench]]
name = "metal"
harness = false

[[bench]]
name = "alloc"
harness = false

[[bench]]
name = "ns_array_from"
harness = false

[[example]]
name = "am-device-list"
required-features = ["am"]

[[example]]
name = "am-device-mount-dev-image"
required-features = ["am"]

[[example]]
name = "audio"

[lib]
# proc-macro = true
#crate-type = ["staticlib", "rlib"]
#crate-type = ["staticlib", "rlib"]


[package.metadata.playground]
features = ["full"]
