[package]
name = "cidre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ["full"]

full = [
  "private",

  "blocks",
  "async",

  "am",
  "at",
  "ca",
  "ci",
  "cm",
  "ct",
  "av",
  "cf",
  "cg",
  "ns",
  "vt",
  "sc",
  "mtl",
  "mlc",
  "cv",
  "objc",
  "mps",
  "mpsg",
  "dispatch",
  "simd",
  "cat",
  "vn",
  "io"
]

# Turn on private API
private = []

blocks = []
async = ["dep:parking_lot"]

am = ["private", "cf", "dep:tokio"]
at = ["cat"]
av = ["ns"]
ca = ["ns"]
cm = ["at"]
cv = ["cf"]
ci = ["ns", "cf"]
cf = []
cg = ["cf", "dispatch", "io"]
ns = ["objc"]
sc = ["ns"]
vt = ["cf", "cv", "cg", "cm"]
mtl = ["ns"]
mlc = ["mtl"]
dispatch = ["cf", "ns"]
io = ["cf"]
sn = ["ns"]
cat = []
vn = ["ns"]
ct = ["cf", "cg"]
mps = ["mtl"]
mpsg = ["mps"]
simd = []
objc = ["dep:cidre-macros"]

[dependencies]

tokio = { version = "1", optional = true, features = ["macros", "rt", "rt-multi-thread", "time", "net", "process", "io-util"] }
parking_lot = { version = "0.12.0", optional = true }
cidre-macros = { optional = true, path = "../cidre-macros"}

[dev-dependencies]
criterion = "0.3"
# rt = { path = "../../rt"}
ndarray = "0.15"
linfa = "0.6.1"
linfa-clustering = "0.6.1"
linfa-reduction = "0.6.1"
clap = { version = "4.1.4", features = ["default", "derive"] }

[[bench]]
name = "metal"
harness = false

[[bench]]
name = "alloc"
harness = false

[[bench]]
name = "ns_array_from"
harness = false

[[example]]
name = "device-list"
required-features = ["am"]

[[example]]
name = "device-mount-dev-image"
required-features = ["am"]

[[example]]
name = "audio"

[lib]
# proc-macro = true
#crate-type = ["staticlib", "rlib"]
#crate-type = ["staticlib", "rlib"]


[package.metadata.playground]
features = ["full"]
