[package]
name = "cidre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ["full"]

full = [
  "private",
  "blocks",
  "async",

  "am",
  "at",
  "ca",
  "ci",
  "cm",
  "av",
  "cf",
  "cg",
  "ns",
  "vt",
  "sc",
  "mtl",
]

# Turn on private API
private = []

blocks = []
async = []

am = ["private", "cf"]
at = []
av = ["ns"]
ca = []
cm = []
ci = ["ns", "cf"]
cf = []
cg = []
ns = []
sc = ["ns"]
vt = ["cf"]
mtl = ["ns"]

[dependencies]

once_cell = "1.17.0"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "time", "net", "process", "io-util"] }
parking_lot = "0.12.0"
cidre-macros = { path = "../cidre-macros"}

[dev-dependencies]
criterion = "0.3"
flume = { version = "0.10", features = ["async"] }
# rt = { path = "../../rt"}
ndarray = "0.15"
linfa = "0.6.1"
linfa-clustering = "0.6.1"
linfa-reduction = "0.6.1"
clap = { version = "4.1.4", features = ["default", "derive"] }

[[bench]]
name = "metal"
harness = false

[[bench]]
name = "alloc"
harness = false

[[example]]
name = "device_list"
required-features = ["am"]

[[example]]
name = "device_mount_dev_image"
required-features = ["am"]

[[example]]
name = "audio"

[lib]
# proc-macro = true
#crate-type = ["staticlib", "rlib"]
#crate-type = ["staticlib", "rlib"]


[package.metadata.playground]
features = ["full"]
